# Generated by Django 4.1.7 on 2023-03-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('task', models.TextField(blank=True, max_length=4096, verbose_name='Поставленная задача')),
                ('photo', models.FileField(blank=True, upload_to='photos', verbose_name='Фото')),
                ('status', models.FloatField(default=0, verbose_name='Процент выполнения')),
                ('is_done', models.BooleanField(default=False, verbose_name='Все выполнили')),
                ('lost_deadline_count', models.IntegerField(default=0, verbose_name='Просрочившие исполнители')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО пользователя')),
                ('username', models.CharField(max_length=255, verbose_name='Никнейм пользователя')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_done', models.BooleanField(default=False, verbose_name='Задача выполнена')),
                ('is_not_deadline_lost', models.BooleanField(default=True, verbose_name='Задача не просрочена')),
                ('role', models.ForeignKey(default='Исполнитель', on_delete=django.db.models.deletion.PROTECT, related_name='user_task_role', to='backend.role', to_field='name')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='backend.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='backend.telegramuser')),
            ],
            options={
                'verbose_name': 'Ответственный за задачу',
                'verbose_name_plural': 'Ответственные за задачи',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='backend.telegramuser'),
        ),
    ]
