# Generated by Django 4.1.7 on 2023-03-21 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_task_datetime_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed_task',
            field=models.BooleanField(default=False, verbose_name='Закрытая задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 21, 3, 23, 6, 324155), verbose_name='Дэдлайн'),
        ),
    ]
