# Generated by Django 4.1.7 on 2023-04-04 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_task_datetime_deadline_alter_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл отчета'),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='report_text',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Текст отчета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 4, 52, 19, 147746), verbose_name='Дэдлайн'),
        ),
    ]
