# Generated by Django 4.1.7 on 2023-04-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_telegramuser_done_tasks_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime_deadline',
            field=models.DateTimeField(blank=True, verbose_name='Дэдлайн'),
        ),
    ]
